### ISSUE TITLE
Possibility to invoke make with a number of jobs

### ISSUE THREAD

**Issue by dead-tech** [dead-tech/pre-commit-cmake#2]
Very often compiling the whole project could take a long time, therefore being able to specify a number of jobs for the make command could really help speed up the compilation process.

Proposed solution

```yaml
repos:
  - repo: https://github.com/dead-tech/pre-commit-cmake
    rev: 'v0.0.3'
    hooks:
      - id: cmake-build
        args: [--release, '--build-dir <path>', '--jobs 5']
```
